Authentication
Tejinder15/versla-store pull request #5
Opened 2022-03-23 13:40 UTC by Tejinder15

# Added Authentication

## Things to check :
1. Whether you are able to access cart Page, wishlist Page without login
2. whether you are able to successfully login or not
3. whether you are able to logout after logging in

2022-03-23 15:29 UTC, Abhijeet43 requested changes
Change the pointer on you login button to cursor

2022-03-23 15:29 UTC, Abhijeet43 commented on src/Components/Header/Header.jsx
> +    }
Hey @Tejinder15 can you just tell is there any specific reason of using async here?

2022-03-23 17:42 UTC, Abhijeet43 approved these changes
The Code is working well.. Code structure is also good

2022-03-24 05:40 UTC, mohammed-sas approved these changes
1.auth context has been written well
2.functionalities are working as desired
3.overall code is fine

2022-03-24 05:41 UTC, merged